version: 2.1
orbs:
  github-cli: circleci/github-cli@2.3.0

jobs:
  cypress:
    docker:
      - image: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - checkout
      - github-cli/setup

workflows:
  generic-api:
    jobs:
      - cypress
